apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp
  labels:
    app: myapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: myapp-backend
        image: stacksimplify/kube-helloworld:1.0.0
        ports:
        - containerPort: 8080
