apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end-nginx-app
  template:
    metadata:
      labels:
        app: front-end-nginx-app
    spec:
      containers:
      - name: front-end-nginx-app
        image: stacksimplify/kube-frontend-nginx:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
