apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-nginx-app
  labels:
    app: front-end-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end-nginx-app
  template:
    metadata:
      labels:
        app: front-end-nginx-app
    spec:
      containers:
      - name: front-end-nginx-app
        image: stacksimplify/kube-frontend-nginx:1.0.0
        ports:
        - containerPort: 80
