apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myazurepvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: my-azure-file-sc
