apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword11

        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name : mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: usermanagement-db-creation-script
          mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-manged-disc-pvc
        - name: usermanagement-db-creation-script
          configMap:
            name: db-creation
  strategy:
    type: Recreate
    
